[package]
name = "jove/lumber-simulation"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "lukadev-0/typed-promise@4.0.2"
RandomOption = "ernisto/random-option@0.1.0"
Replication = "ernisto/replication@0.1.2"
Wrapper = "ernisto/wrapper@0.4.2"
Entity = "ernisto/entity@0.1.0"
Signal = "ernisto/signal@0.1.1"
Cache = "ernisto/cache@0.3.1"
Ray = "ernisto/ray@0.1.2"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
Replicator = "ernisto/replicator@0.2.1"

[dev-dependencies]
TestEZ = "ruizukun-dev/testez@0.4.8"

[place]
shared-packages = "game.ReplicatedStorage.Packages"